bug/fix resources
meganz/AndroidDocumentScanner pull request #1
Opened 2020-10-13 15:24 UTC by Gnzlt

## What does this implement/fix? Explain your changes.
- Added new scan icon
- Compressed existing resources
- Replaced hardcoded Strings with placeholders
- Added context to new Strings to be translated.

## Any relevant logs, error output, etc?
...

## Any other comments?
...

## Where has this been tested?

- **Devices/Simulators:** 
Pixel 4

- **OS Version:** 
Android 11

2020-10-14 09:59 UTC, Gnzlt commented on documentscanner/build.gradle
> +            abiFilters 'arm64-v8a', 'armeabi-v7a'
As [previously discussed](https://megaconz.slack.com/archives/CBV4ZRC1L/p1598282116010200), we decided to stick to `armeabi-v7a` and `arm64-v8a` due to limitations with APK size.

2020-10-19 12:48 UTC, javiergm1983 commented on documentscanner/src/main/res/values/strings.xml
>  </resources>
Rename this file by `strings_document_scanner.xml` in order to upload it to Babel. The filename `strings.xml` is already in use in Babel for the strings of the Android app.

2020-10-19 16:13 UTC, javiergm1983 requested changes
Some strings improvements needed. Please take a look to my comments.

In addition there is a problem with other string. As you can see in the following screenshot it says "Upload" where it should say "Add" (see the [design](https://projects.invisionapp.com/d/main#/console/13743399/427943818/preview#project_console))

![Screenshot_20201019-175719](https://user-images.githubusercontent.com/9530227/96477419-c1916f80-1236-11eb-9acb-115cf1d5d779.png)

2020-10-19 16:13 UTC, javiergm1983 commented on documentscanner/src/main/res/values/strings_document_scanner.xml
> +</resources>
Add screenshots for each of these strings to the screenshots shared folder.

2020-10-20 09:36 UTC, javiergm1983 requested changes
I have seen some other problems with the strings. Sorry for not seeing and reporting them yesterday along with the other issues.

2020-10-20 09:36 UTC, javiergm1983 commented on documentscanner/src/main/res/values/strings_document_scanner.xml
> +    <string name="app_name">MEGA Document Scanner</string>
Please, also add a context for the app name string. I'm sure that translators wil require it.
For example: "Name of the MEGA Document Scanner. Keep uppercase."

```suggestion
    <string name="app_name" context="Name of the MEGA Document Scanner. Keep uppercase.">MEGA Document Scanner</string>
```

2020-10-20 09:36 UTC, javiergm1983 commented on documentscanner/src/main/res/values/strings_document_scanner.xml
> +    <string name="scan_file_type_jpg" context="Document scanner JPG file type option">JPG</string>
These two strings are no translatables, so they should not be included in the strings file that we will upload to Babel. They should be converted as constants or moved to a separated file (for example `strings_donottranslate.xml`) like in the MEGA Android app project.

2020-10-20 09:36 UTC, javiergm1983 commented on documentscanner/src/main/res/values/strings_document_scanner.xml
> +    <string name="scan_format_page_count" context="Format text to show current page number out of total">%1$d / %2$d</string>
Same here, this is a no translatable string.

2020-10-20 11:51 UTC, javiergm1983 approved these changes

2020-10-20 11:55 UTC, javiergm1983 commented
I think everything is fine now. @ash-mega , can you take a look at it too?

2020-10-20 12:04 UTC, merged