bug/UI inconsistencies
meganz/AndroidDocumentScanner pull request #24
Opened 2021-03-25 14:42 UTC by Gnzlt

## What does this implement/fix? Explain your changes.
- AND-12764
- AND-12773
- AND-12769
- AND-12767

## Any relevant logs, error output, etc?
...

## Any other comments?
...

## Where has this been tested?

- **Devices/Simulators:** 
Google Pixel 4

- **OS Version:** 
Android 11

2021-03-26 14:23 UTC, Piasy commented on build.gradle
> +        kotlinVersion = "1.4.31"
Should we use the same version as MEGA app repo?

2021-03-26 14:24 UTC, Piasy commented
Everything looks fine, just small feedback.

And what's the expected behavior of https://jira.developers.mega.co.nz/browse/AND-12773 ? Currently it's still not cancellable while saving.

2021-03-26 17:06 UTC, Gnzlt commented
> And what's the expected behavior of https://jira.developers.mega.co.nz/browse/AND-12773 ? Currently it's still not cancellable while saving.

It has been replaced by a [Progress Dialog](https://meganz.invisionapp.com/d/#/console/13743399/446859883/) which is not cancelable.

2021-03-29 01:41 UTC, Piasy approved these changes

2021-04-07 15:32 UTC, javiergm1983 commented
@Gnzlt I have changed the base branch because it should be `develop` like for any other PR.
@Piasy please review and approve again.

2021-04-08 01:29 UTC, Piasy approved these changes

2021-04-14 15:44 UTC, javiergm1983 approved these changes

2021-04-15 10:53 UTC, ash-mega requested changes
Hi @Gnzlt , the code changes are fine and other bugs are fixed except [this one](https://jira.developers.mega.co.nz/browse/AND-12767).
Follow the steps provided by Eve, the issue remains,could you please confirm? Cheers.

2021-04-15 11:08 UTC, Gnzlt commented
> Hi @Gnzlt , the code changes are fine and other bugs are fixed except [this one](https://jira.developers.mega.co.nz/browse/AND-12767).
> Follow the steps provided by Eve, the issue remains,could you please confirm? Cheers.

Hey @ash-mega, I've just checked and it works as expected. Please make sure you are using the latest version from this branch when building.
```
implementation 'com.github.meganz:AndroidDocumentScanner:96c16ff4b4'
```

https://user-images.githubusercontent.com/5398754/114859764-7a51f900-9deb-11eb-8273-3959a0af3825.mp4

2021-04-16 01:32 UTC, ash-mega commented
Hi @Gnzlt , you're right, the issue is fixed. All good, approved.

2021-04-16 01:33 UTC, ash-mega approved these changes

2021-04-16 01:33 UTC, merged